Add access to the NewKnownGood field in a SubscribedUSKUpdate message.
Bombe/jFCPlib pull request #4
Opened 2020-08-01 05:41 UTC by debbiedub

I need access to the NewKnownGood field when subscribing to USKs. Here is a suggestion to provide it in the lib.

2020-08-01 16:16 UTC, Bombe approved these changes

2020-08-02 11:20 UTC, Bombe requested changes
Okay, while the general changes are fine, can you rebase it on current `next`, please?

2020-08-02 16:12 UTC, debbiedub commented
Done.

I assumed that you will want this merge request to merge into the next branch and not to carry all other changes from next into master. I have therefore changed the base branch of the merge request.

2020-08-02 19:13 UTC, Bombe commented
> Done.

Not really?

Your work seems to be based on a second root commit that has nothing to do with the current `main` and `next` branches… I have no idea how you got there but please check again; current `next` is at `1595c70e1db562c403011a894b9355937c56ca0a`, current `main` is at `f6658f9e2121cf6f08ff567624cc9b83dcad0eb5`.

2020-08-02 19:14 UTC, Bombe commented
Hmm, or maybe I got something mixed up here, let me check.

2020-08-02 19:20 UTC, Bombe commented
Yep, sorry, my bad! I imported your changes into the wrong repository, no wonder it didn’t match up with anything. 😄

2020-08-02 19:21 UTC, merged

2020-08-02 19:22 UTC, Bombe commented
Thank you!